robot: "h1"  # Robot name, "go2", "b2", "b2w", "h1", "go2w", "g1"
robot_scene: "scene.xml" # Robot scene, /unitree_robots/[robot]/scene.xml

domain_id: 1    # Domain id
interface: "eno1" # Interface

# domain_id: 1
# interface: "lo"

use_joystick: 0 # Simulate Unitree WirelessController using a gamepad
joystick_type: "betop" # support "xbox", "switch" , "yahboom" and "betop" gamepad layout
joystick_device: "/dev/input/js0" # Device path
joystick_bits: 16 # Some game controllers may only have 8-bit accuracy

# use_joystick: 1 # Simulate Unitree WirelessController using a gamepad
# joystick_type: "xbox" # support "xbox", "switch" , "yahboom" and "betop" gamepad layout
# joystick_device: "/dev/input/js0" # Device path
# joystick_bits: 16

print_scene_information: 1 # Print link, joint and sensors information of robot

enable_elastic_band: 1 # Virtual spring band, used for lifting h1

# Depth camera settings
enable_depth: 1
depth_width: 320
depth_height: 240
crop_left: 8
far_clip: 10.0
near_clip: 0.175
depth_dt: 0.1 # Depth camera update interval (s)
